server:
  port: 8080

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: user-service
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/user-service
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kokodo?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: BITBIT123 #1234

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# Token 유효기간 1일
token:
  expiration_time: 86400000
  secret: member_token
