
server:
  port: 0

spring:
  application:
    name: member-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kokodo?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: BITBIT123
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

    properties:
      hibernate:
        show-sql: true
        format_sql: true
  sql:
    init:
      mode: always

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

token:
  member:
    access:
      exp: 86400000
    refresh:
      exp: 604800000
    secret: member_token

oauth:
  naver:
    token-url: https://nid.naver.com/oauth2.0/token
    me-url: https://openapi.naver.com/v1/nid/me
    grant-type: authorization_code
    client-id:
    client-secret:
  kakao:
    token-url: https://kauth.kakao.com/oauth/token
    me-url: https://kapi.kakao.com/v2/user/me
    grant-type: authorization_code
    client-id:
    client-secret: